services:
  # Ollama and API
  ollama:
    image: ollama/ollama:0.3.5
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash" , "/entrypoint.sh"]
  
  ## Mongo database
  mongodb:
    build:
      context: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: "27017"
    ports:
      - 27017:27017
    attach: false
    depends_on:
      - ollama

  ## NextJs web application UI
  nextjs-ui:
    build:
      context: ./
      dockerfile: dev.DockerFile
    environment:
      NEXT_PUBLIC_APPLICATION_NAME: ${NEXT_PUBLIC_APPLICATION_NAME}
      MONGODB_URL: ${MONGODB_URL}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_EMBEDDINGS_MODEL: ${OLLAMA_EMBEDDINGS_MODEL}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - ollama
      - mongodb

volumes:
  ollama:
  mongodb_data:
  mongodb_config:
